version: 2

models:
  - name: CA_aggregate_customer_analysis_data
    description: "Gather data required for analysing customers into single table."
    config:
      materialized: table

sources:
  - name: bigquery_nettikauppasimulaattori
    database: nettikauppasimulaattori # BigQuery project.
    schema: store_operational         # BigQuery dataset.
    tables:
      - name: customers
      - name: orders
      - name: order_items
      - name: products

  - name: bigquery_nettikauppasimulaattori_constants
    database: nettikauppasimulaattori
    schema: store_constants
    tables:
      - name: delivery_types
      - name: orderstatus_types
      - name: product_categories