version: 2

models:
  - name: CA_aggregate_customer_analysis_data
    description: "Gather data required for analysing customers into single table."
    config:
      materialized: table

  - name: PA_individual_products
    description: "Get statistics for each individual product."
    config:
      materialized: table

  - name: PA_product_categories
    description: "Get statistics for each product category."
    config:
      materialized: table

sources:
  - name: bigquery_nettikauppasimulaattori
    database: nettikauppasimulaattori # BigQuery project.
    schema: store_operational         # BigQuery dataset.
    tables:
      - name: customers
      - name: orders
      - name: order_items
      - name: products
    
  - name: nettikauppasimulaattori_data_warehouse
    database: nettikauppasimulaattori
    schema: store_analysis_dbt

    freshness:
      warn_after:
        count: 12
        period: hour
      error_after:
        count: 24
        period: hour
    loaded_at_field: "CAST(created_at AS TIMESTAMP)"

    tables:
      - name: import_customers
      - name: import_order_items
      - name: import_orders
      - name: import_products


#  - name: bigquery_nettikauppasimulaattori_constants
#    database: nettikauppasimulaattori
#    schema: store_constants
#    tables:
#      - name: delivery_types
#      - name: orderstatus_types
#      - name: product_categories